// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc103.Swerve2017Test.subsystems;

import org.usfirst.frc103.Swerve2017Test.RobotMap;

import static org.usfirst.frc103.Swerve2017Test.RobotMap.climberLiftWinch;

import org.usfirst.frc103.Swerve2017Test.Robot;
import com.ctre.CANTalon;

import edu.wpi.first.wpilibj.command.Subsystem;




public class Climber extends Subsystem {


    private final CANTalon liftWinch = RobotMap.climberLiftWinch;
    
    public void Climb(){
    	
    	liftWinch.set(0.5);
    	
    }

	@Override
	protected void initDefaultCommand() {
		
		
		
	}
}

