package org.usfirst.frc103.Swerve2017Test;

import com.ctre.CANTalon;
import com.ctre.CANTalon.FeedbackDevice;
import com.ctre.CANTalon.TalonControlMode;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    public static CANTalon driveLeftFront;
    public static CANTalon driveLeftRear;
    public static CANTalon driveRightFront;
    public static CANTalon driveRightRear;
    public static CANTalon steerLeftFront;
    public static CANTalon steerLeftRear;
    public static CANTalon steerRightFront;
    public static CANTalon steerRightRear;
    public static CANTalon shooterFlyWheel;
    public static CANTalon shooterElevator;
    public static CANTalon gearManipulatorDoors;
    public static CANTalon climberLiftWinch;

    public static void init() {
        driveLeftFront = new CANTalon(10);
        driveLeftFront.setFeedbackDevice(FeedbackDevice.QuadEncoder);
        LiveWindow.addActuator("Drive", "LeftFrontDrive", driveLeftFront);
        
        driveLeftRear = new CANTalon(11);
        driveLeftRear.setFeedbackDevice(FeedbackDevice.QuadEncoder);
        LiveWindow.addActuator("Drive", "LeftRearDrive", driveLeftRear);
        
        driveRightFront = new CANTalon(12);
        driveRightFront.setFeedbackDevice(FeedbackDevice.QuadEncoder);
        driveRightFront.setInverted(true);
        LiveWindow.addActuator("Drive", "RightFrontDrive", driveRightFront);
        
        driveRightRear = new CANTalon(13);
        driveRightRear.setFeedbackDevice(FeedbackDevice.QuadEncoder);
        driveRightRear.setInverted(true);
        LiveWindow.addActuator("Drive", "RightRearDrive", driveRightRear);
        
        steerLeftFront = new CANTalon(16);
        steerLeftFront.setFeedbackDevice(FeedbackDevice.AnalogEncoder);
        steerLeftFront.setPID(10.0, 0.02, 0.0);
        steerLeftFront.setIZone(100);
        steerLeftFront.setAllowableClosedLoopErr(5);
        steerLeftFront.changeControlMode(TalonControlMode.Position);
        LiveWindow.addActuator("Steer", "LeftFrontSteer", steerLeftFront);
        
        steerLeftRear = new CANTalon(17);
        steerLeftRear.setFeedbackDevice(FeedbackDevice.AnalogEncoder);
        steerLeftRear.setPID(10.0, 0.02, 0.0);
        steerLeftRear.setIZone(100);
        steerLeftRear.setAllowableClosedLoopErr(5);
        steerLeftRear.changeControlMode(TalonControlMode.Position);
        LiveWindow.addActuator("Steer", "LeftRearSteer", steerLeftRear);
        
        steerRightFront = new CANTalon(18);
        steerRightFront.setFeedbackDevice(FeedbackDevice.AnalogEncoder);
        steerRightFront.setPID(10.0, 0.02, 0.0);
        steerRightFront.setIZone(100);
        steerRightFront.setAllowableClosedLoopErr(5);
        steerRightFront.changeControlMode(TalonControlMode.Position);
        LiveWindow.addActuator("Steer", "RightFrontSteer", steerRightFront);
        
        steerRightRear = new CANTalon(19);
        steerRightRear.setFeedbackDevice(FeedbackDevice.AnalogEncoder);
        steerRightRear.setPID(10.0, 0.02, 0.0);
        steerRightRear.setIZone(100);
        steerRightRear.setAllowableClosedLoopErr(5);
        steerRightRear.changeControlMode(TalonControlMode.Position);
        LiveWindow.addActuator("Steer", "RightRearSteer", steerRightRear);
        
        shooterFlyWheel = new CANTalon(2);
        shooterFlyWheel.setInverted(true);
        shooterFlyWheel.setFeedbackDevice(FeedbackDevice.CtreMagEncoder_Relative);
        LiveWindow.addActuator("Shooter", "FlyWheel", shooterFlyWheel);
        
        shooterElevator = new CANTalon(3);
        shooterElevator.setInverted(true);
        LiveWindow.addActuator("Shooter", "Elevator", shooterElevator);
        
        gearManipulatorDoors = new CANTalon(1);
        LiveWindow.addActuator("GearManipulator", "Doors", gearManipulatorDoors);
        
        climberLiftWinch = new CANTalon(4);
        LiveWindow.addActuator("Climber", "LiftWinch", climberLiftWinch);
    }
}
